import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ResponsiveAppBar } from '@ui/app-bar/app-bar'
import {NextAuthProvider } from "./providers"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Auter AI',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
        <ResponsiveAppBar />
         {children}
        </NextAuthProvider>
        </body>
    </html>
  )
}
