import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { AICPNavBar } from '@ui/aicp-navbar/aicp-navbar'
import {NextAuthProvider, UIProvider } from "./providers"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Auter AI',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UIProvider>
        <NextAuthProvider>
        <AICPNavBar />
         {children}
        </NextAuthProvider>
        </UIProvider>
        </body>
    </html>
  )
}
