researcher:
  model: "gpt-3.5"
script_writer:
  model: "gpt-3.5"
voiceover_artist:
  model: "gpt-3.5"
  voice_actor: "ahmed"
storyboard_artist:
  model: SG161222/Realistic_Vision_V2.0
  scheduler: DPMSolverMultistepScheduler
