researcher:
  model: "revgpt-gpt-4"
script_writer:
  model: "revgpt-gpt-4"
voiceover_artist:
  ego_model: "revgpt-gpt-4"
  actor: "zane"
storyboard_artist:
  ego_model: "revgpt-gpt-3.5"
  sd_model: SG161222/Realistic_Vision_V3.0
thumbnail_artist:
  ego_model: "revgpt-gpt-3.5"
  sd_model: SG161222/Realistic_Vision_V3.0
music_composer:
  ego_model: "revgpt-gpt-3.5"
youtube_distributor:
  ego_model: "revgpt-gpt-3.5"
