researcher:
  model: "gpt-4-browsing"
script_writer:
  model: "gpt-3.5"
voiceover_artist:
  ego_model: "gpt-3.5"
  actor: "zane"
storyboard_artist:
  ego_model: "gpt-3.5"
  sd_model: SG161222/Realistic_Vision_V3.0
thumbnail_artist:
  ego_model: "gpt-3.5"
  sd_model: SG161222/Realistic_Vision_V3.0
music_composer:
  ego_model: "gpt-3.5"
youtube_distributor:
  ego_model: "gpt-3.5"
