researcher:
  model: "gpt-3.5"
script_writer:
  model: "gpt-3.5"
voiceover_artist:
  ego_model: "gpt-3.5"
  voice_actor: "zane"
storyboard_artist:
  ego_model: "gpt-3.5"
  sd_model: SG161222/Realistic_Vision_V2.0
