/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/actors/{actor_id}": {
    /**
     * Get Actor
     * @description Get an actor
     *     by reading yamls/cast/actors directory
     *     the id is the filename
     */
    get: operations["videocreator_routers_actors_get_actor"];
  };
  "/api/actors/": {
    /**
     * Get Actors
     * @description Get all actors
     * by reading yamls/cast/actors directory
     */
    get: operations["videocreator_routers_actors_get_actors"];
  };
  "/api/programs/{program_id}": {
    /**
     * Get Program
     * @description Get a program
     * by reading yamls/programs directory
     * the id is the filename
     */
    get: operations["videocreator_routers_programs_get_program"];
  };
  "/api/programs/": {
    /**
     * Get Programs
     * @description Get all programs
     * by reading yamls/programs directory
     */
    get: operations["videocreator_routers_programs_get_programs"];
  };
  "/api/projects/": {
    /**
     * Get Projects
     * @description Get all projects
     * by reading output/projects directory
     */
    get: operations["videocreator_routers_projects_get_projects"];
    /**
     * Create Project
     * @description Create a project
     * create a directory output/projects/{project_id}
     */
    post: operations["videocreator_routers_projects_create_project"];
  };
  "/api/projects/{project_id}": {
    /**
     * Get Project
     * @description Get a project
     * by reading output/projects/{project_id}
     */
    get: operations["videocreator_routers_projects_get_project"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /**
     * AICPActor
     * @description Class encapsulating the actor for an AICP video.
     */
    AICPActor: {
      /** Name */
      name: string;
      /** Bio */
      bio: string | null;
      /** Catch Phrase */
      catch_phrase: string | null;
      /** Physical Description */
      physical_description: string | null;
      /** Speaker */
      speaker: string;
      /**
       * Speaker Text Temp
       * @default 0.7
       */
      speaker_text_temp?: number;
      /**
       * Speaker Waveform Temp
       * @default 0.7
       */
      speaker_waveform_temp?: number;
    };
    /**
     * AICPProductionConfig
     * @description Class encapsulating the production config for an AICP video.
     */
    AICPProductionConfig: {
      /**
       * Video Width
       * @default 1920
       */
      video_width?: number;
      /**
       * Video Height
       * @default 1080
       */
      video_height?: number;
      /**
       * Sd Base Image Width
       * @default 768
       */
      sd_base_image_width?: number;
      /**
       * Sd Base Image Height
       * @default 432
       */
      sd_base_image_height?: number;
      /**
       * Enable Subtitles
       * @default false
       */
      enable_subtitles?: boolean;
      /**
       * Voiceline Synced Storyboard
       * @default false
       */
      voiceline_synced_storyboard?: boolean;
      /**
       * Num Images Per Scene
       * @default 1
       */
      num_images_per_scene?: number;
    };
    /**
     * AICPProgram
     * @description Class encapsulating the program for an AICP video.
     */
    AICPProgram: {
      /** Title */
      title: string;
      /** Description */
      description: string;
      /** Prompt Placeholder Text */
      prompt_placeholder_text: string;
      /** Script Rules */
      script_rules?: string | null;
      /** Storyboard Rules */
      storyboard_rules?: string | null;
      /** Music Rules */
      music_rules?: string | null;
    };
    /**
     * AICPProject
     * @description Class encapsulating the project for an AICP video.
     */
    AICPProject: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Description */
      description?: string | null;
      program: components["schemas"]["AICPProgram"];
      production_config: components["schemas"]["AICPProductionConfig"];
      /**
       * Actors
       * @default []
       */
      actors?: components["schemas"]["AICPActor"][];
      /** Seed */
      seed: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * Get Actor
   * @description Get an actor
   *     by reading yamls/cast/actors directory
   *     the id is the filename
   */
  videocreator_routers_actors_get_actor: {
    parameters: {
      path: {
        actor_id: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  /**
   * Get Actors
   * @description Get all actors
   * by reading yamls/cast/actors directory
   */
  videocreator_routers_actors_get_actors: {
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  /**
   * Get Program
   * @description Get a program
   * by reading yamls/programs directory
   * the id is the filename
   */
  videocreator_routers_programs_get_program: {
    parameters: {
      path: {
        program_id: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  /**
   * Get Programs
   * @description Get all programs
   * by reading yamls/programs directory
   */
  videocreator_routers_programs_get_programs: {
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  /**
   * Get Projects
   * @description Get all projects
   * by reading output/projects directory
   */
  videocreator_routers_projects_get_projects: {
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  /**
   * Create Project
   * @description Create a project
   * create a directory output/projects/{project_id}
   */
  videocreator_routers_projects_create_project: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["AICPProject"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  /**
   * Get Project
   * @description Get a project
   * by reading output/projects/{project_id}
   */
  videocreator_routers_projects_get_project: {
    parameters: {
      path: {
        project_id: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
}
