/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/projects": {
    /**
     * List Projects
     * @description Returns a list of all projects.
     */
    get: operations["videocreator_api_list_projects"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /**
     * AICPActor
     * @description Class encapsulating the actor for an AICP video.
     */
    AICPActor: {
      /** Name */
      name: string;
      /** Bio */
      bio: string | null;
      /** Catch Phrase */
      catch_phrase: string | null;
      /** Physical Description */
      physical_description: string | null;
      /** Speaker */
      speaker: string;
      /**
       * Speaker Text Temp
       * @default 0.7
       */
      speaker_text_temp?: number;
      /**
       * Speaker Waveform Temp
       * @default 0.7
       */
      speaker_waveform_temp?: number;
    };
    /**
     * AICPProductionConfig
     * @description Class encapsulating the production config for an AICP video.
     */
    AICPProductionConfig: {
      /**
       * Video Width
       * @default 1920
       */
      video_width?: number;
      /**
       * Video Height
       * @default 1080
       */
      video_height?: number;
      /**
       * Sd Base Image Width
       * @default 768
       */
      sd_base_image_width?: number;
      /**
       * Sd Base Image Height
       * @default 432
       */
      sd_base_image_height?: number;
      /**
       * Enable Subtitles
       * @default false
       */
      enable_subtitles?: boolean;
      /**
       * Voiceline Synced Storyboard
       * @default false
       */
      voiceline_synced_storyboard?: boolean;
      /**
       * Num Images Per Scene
       * @default 1
       */
      num_images_per_scene?: number;
    };
    /**
     * AICPProgram
     * @description Class encapsulating the program for an AICP video.
     */
    AICPProgram: {
      /** Title */
      title: string;
      /** Description */
      description: string;
      /** Prompt Placeholder Text */
      prompt_placeholder_text: string;
      /** Script Rules */
      script_rules?: string | null;
      /** Storyboard Rules */
      storyboard_rules?: string | null;
      /** Music Rules */
      music_rules?: string | null;
    };
    /**
     * AICPProject
     * @description Class encapsulating the project for an AICP video.
     */
    AICPProject: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Description */
      description?: string | null;
      program: components["schemas"]["AICPProgram"];
      production_config: components["schemas"]["AICPProductionConfig"];
      /**
       * Actors
       * @default []
       */
      actors?: components["schemas"]["AICPActor"][];
      /** Seed */
      seed: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * List Projects
   * @description Returns a list of all projects.
   */
  videocreator_api_list_projects: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["AICPProject"][];
        };
      };
    };
  };
}
